/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ppsea_cocosjava_WindowsAdapter */

#ifndef _Included_com_ppsea_cocosjava_WindowsAdapter
#define _Included_com_ppsea_cocosjava_WindowsAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ppsea_cocosjava_WindowsAdapter
 * Method:    setupView
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ppsea_cocosjava_WindowsAdapter_setupView
  (JNIEnv *, jclass, jint);
/*
 * Class:     com_ppsea_cocosjava_WindowsAdapter
 * Method:    setSearchPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ppsea_cocosjava_WindowsAdapter_setSearchPath
  (JNIEnv *, jclass, jstring);
/*
 * Class:     com_ppsea_cocosjava_WindowsAdapter
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ppsea_cocosjava_WindowsAdapter_resize
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ppsea_cocosjava_WindowsAdapter
 * Method:    procMessage
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_ppsea_cocosjava_WindowsAdapter_procMessage
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_ppsea_cocosjava_WindowsAdapter
 * Method:    mainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ppsea_cocosjava_WindowsAdapter_mainLoop
  (JNIEnv *, jclass);

/*
 * Class:     com_ppsea_cocosjava_WindowsAdapter
 * Method:    distroyView
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ppsea_cocosjava_WindowsAdapter_distroyView
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
